version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DEFAULT_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    hostname: mongo-server
    networks:
      - tempu_net
    restart: always

  tempusalert:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tempusalert-be
    container_name: backend
    volumes:
      - .env:/tempusalert-be/.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    hostname: backend
    networks:
      - tempu_net
    restart: always

volumes:
  mongo:

networks:
  tempu_net:
    driver: bridge