version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DEFAULT_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
    restart: always
    hostname: mongo-server
    networks:
      - tempu_net

  tempusalert:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    volumes:
      - .env:/usr/lib/tempusalert-be/.env
    ports:
      - "8080:8080"
    restart: always
    hostname: backend
    networks:
      - tempu_net

volumes:
  mongo:

networks:
  tempu_net:
    driver: bridge